project_name: conbukun

before:
  hooks:
    - go mod tidy

builds:
  - binary: bin/conbukun
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
    main: cmd/conbukun/main.go

release:
  prerelease: auto