apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: conbukun
    newName: ghcr.io/ebiiim/conbukun
    newTag: "latest"

namespace: conbukun

namePrefix: ""
nameSuffix: ""

resources:
  - base/sts.yaml
  # - secret.yaml

patchesStrategicMerge: []

patches:
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: conbukun
    # uncomment if you want to set storageClassName
    patch: |-
      # - op: add
      #   path: /spec/volumeClaimTemplates/0/spec/storageClassName
      #   value: longhorn
