apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: conbukun
  name: conbukun
spec:
  serviceName: conbukun
  selector:
    matchLabels:
      app: conbukun
  replicas: 1
  template:
    metadata:
      labels:
        app: conbukun
    spec:
      containers:
        - name: conbukun
          image: conbukun
          command:
            - conbukun
            - -v=5
            - -save-dir=/data
          env:
            - name: CONBUKUN_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: conbukun-secrets
                  key: auth_token
            - name: CONBUKUN_GUILD_ID
              valueFrom:
                secretKeyRef:
                  name: conbukun-secrets
                  key: guild_id
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 800m
              memory: 512Mi
          volumeMounts:
            - name: conbukun-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: conbukun-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
