name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch tags
          submodules: recursive
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: Run tests
        run: make test
